events:
    - schedule: rate(2 hours)

websites:    
    - chewy:
        url: https://www.chewy.com/arm-hammer-litter-multi-cat-slide/dp/140856
        xpath: //div[@id='pricing']//ul[@class='product-pricing']//li[@class='our-price']//p[@class='price']//span
        original: $14.99        
    - 搬瓦工:
        url: https://bwh88.net/cart.php?a=add&pid=72
        xpath: //div[@id='order-web20cart']//h1
        original: Oops, there's a problem...
        
    - Ring Fit Walmart:
        url: https://www.walmart.com/ip/Nintendo-Switch-Ring-Fit-Adventure-Black/434503657
        xpath: //div[@class='prod-ProductOffer-oosMsg prod-PaddingTop--xxs']//span
        original: Out of stock
        
    - Ring Fit Target:
        url: https://www.target.com/p/ring-fit-adventure-nintendo-switch/-/A-76593324
        xpath: //div[@data-test='oosDeliveryOption']
        original: Not available
        
    - Ring Fit Game Stop:
        url: https://www.gamestop.com/video-games/switch/games/products/ring-fit-adventure/11097187.html
        xpath: //div[@class='availability-msg']//div
        original: THIS ITEM IS CURRENTLY NOT AVAILABLE ONLINE
        
    - MIXED-MATERIAL WRAP DRESS:
        url: https://www.toryburch.com/mixed-material-wrap-dress/57281.html?color=001&size=XXS
        xpath: //div[@data-id='ProductInformation']//div[@data-id='PriceContainer']//span
        original: $598
        
    - Mixed Material Wrap Dress:
        url: https://www.saksfifthavenue.com/tory-burch-mixed-material-wrap-dress/product/0400011323740?R=192485307559&P_name=Tory+Burch&Ntt=tory+burch&N=0+4294881840
        xpath: //ul[@class='product-variant-attribute-values']//li//span
        original: SMALL

