events:
    - schedule: rate(2 hours)

websites:      
    - 搬瓦工:
        url: https://bwh88.net/cart.php?a=add&pid=72
        xpath: //div[@id='order-web20cart']//h1
        original: Oops, there's a problem...
        
    - Ring Fit Walmart:
        url: https://www.walmart.com/ip/Nintendo-Switch-Ring-Fit-Adventure-Black/434503657
        xpath: //div[@class='prod-ProductOffer-oosMsg prod-PaddingTop--xxs']//span
        original: Out of stock
        
    - Ring Fit Target:
        url: https://www.target.com/p/ring-fit-adventure-nintendo-switch/-/A-76593324
        xpath: //div[@data-test='nonBuyableShippingMessage']
        original: Temporarily out of stock
        
    - Ring Fit Game Stop:
        url: https://www.gamestop.com/video-games/switch/games/products/ring-fit-adventure/11097187.html
        xpath: //div[@class='availability-msg']//div
        original: THIS ITEM IS CURRENTLY NOT AVAILABLE ONLINE
        
    - MIXED-MATERIAL WRAP DRESS:
        url: https://www.toryburch.com/mixed-material-wrap-dress/57281.html?color=001&size=XXS
        xpath: //div[@data-id='ProductInformation']//div[@data-id='PriceContainer']//span
        original: $598
        
    - JD test:
        url: https://item.jd.hk/3851090.html
        xpath: //*[@id="summary-wrap"]/div/div[1]/div[2]/span/span[2]
        original: "140.00"


